### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by constantinpape** [mobie/mobie-io#118]
Here are the TODOs for the next proper MoBIE-IO release:

MUST (these things need to be implemented / fixed)
- [ ] Remove `is...` checks from https://github.com/mobie/mobie-io/blob/develop/src/main/java/org/embl/mobie/io/ome/zarr/util/ZarrAxes.java#L86-L117; replace all parts where they are used with simpler code like in https://github.com/mobie/mobie-io/blob/develop/src/main/java/org/embl/mobie/io/ome/zarr/util/N5OMEZarrCacheArrayLoader.java#L75-L92
- [ ] Fix loading of spatial transcriptomics data https://github.com/mobie/mobie-io/pull/117
- [ ] clean up test structure, https://github.com/mobie/mobie-io/issues/87

SHOULD (would be nice to have, but not mission critical)
- [ ] Fix loading time-series in Fiji, https://github.com/mobie/mobie-io/issues/105
- [ ] Fix multi-channel names, https://github.com/mobie/mobie-io/issues/105
- [ ] Check that we have all the shared queue loaders, https://github.com/mobie/mobie-io/issues/49

**Comment by constantinpape** [comment]
TODOs for cleaning up the test structure:
- Rename the tests to be more meaningful, something like `dataformats/ome.zarr/...`, `dataformats/n5/...` and so on.
- Add tests for ome.zarr metadata (e.g. scale factors) via refactoring the base test, see https://github.com/mobie/mobie-io/blob/finish-refactor/src/test/java/projects/remote/BaseTest.java#L20-L22
